version: '3'

services:
  backend:
    restart: always
    build: .
    # command: daphne core.asgi:application -b 0.0.0.0 -p 8000
    container_name: backend
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_SERVER_HOST=kafka
      - KAFKA_SERVER_PORT=9094
    volumes:
      - ./:/backend/
    ports:
      - 8000:8000
    depends_on:
      - redis
      - kafka-ui

  celery:
    restart: always
    build: .
    command: celery -A backendviteadmin worker -l info --pool=solo
    volumes:
      - ./:/backend/
    environment:
      - DEBUG=1
      # use tasks call internal api have to use internal host
      - DOCKER_HOST=host.docker.internal
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_SERVER_HOST=kafka
      - KAFKA_SERVER_PORT=9094
    depends_on:
      - redis
      - kafka
  
  celery-beat:
    restart: always
    build: .
    command: celery -A backendviteadmin beat -l info
    volumes:
      - ./:/backend/
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_SERVER_HOST=kafka
      - KAFKA_SERVER_PORT=9094
    depends_on:
      - redis
      - kafka

  frontend:
    restart: always
    build: ../vite-admin/
    container_name: frontend
    ports:
      - 8080:80
    depends_on:
      - backend

  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
      - "9094:9094"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://:9094,OUTSIDE://:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9094,OUTSIDE://${EXTERNAL_IP}:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "9090:8080"
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka:9094'
      KAFKA_CLUSTERS_0_ZOOKEEPER: 'zookeeper:2181'
    depends_on:
      - zookeeper
      - kafka