# Generated by Django 4.1.1 on 2023-02-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('hostname', models.CharField(max_length=128, unique=True)),
                ('ip', models.GenericIPAddressField()),
                ('online', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_online_time', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, choices=[('Szh', 'Suzhou'), ('Sgh', 'Shanghai'), ('Wx', 'Wuxi')], max_length=64, null=True)),
            ],
        ),
    ]
