# Generated by Django 4.1.1 on 2023-02-08 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='executor',
            old_name='created_time',
            new_name='creation_time',
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('creation_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Starting', 'Starting'), ('Running', 'Running'), ('Completed', 'Completed'), ('Error', 'Error'), ('Terminated', 'Terminated'), ('Queuing', 'Queuing'), ('Published', 'Published'), ('Canceled', 'Canceled')], default='Waiting', max_length=64)),
                ('comments', models.CharField(blank=True, max_length=256, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.executor')),
            ],
        ),
    ]
