# Generated by Django 4.1.1 on 2023-02-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_rename_created_time_executor_creation_time_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Idling', 'Idling'), ('Starting', 'Starting'), ('Running', 'Running'), ('Completed', 'Completed'), ('Error', 'Error'), ('Terminated', 'Terminated'), ('Queuing', 'Queuing'), ('Published', 'Published'), ('Canceled', 'Canceled'), ('Scheduled', 'Scheduled')], default='Idling', max_length=64),
        ),
    ]
