# Generated by Django 4.1.1 on 2023-02-15 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_task_scheduled_time_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='published_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reason',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('comments', models.CharField(blank=True, max_length=256, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.executor')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.target'),
        ),
    ]
