# Generated by Django 4.1.1 on 2023-02-15 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_task_is_deleted_task_published_time_task_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='executor',
        ),
    ]
