# Generated by Django 4.1.1 on 2023-02-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_remove_target_executor'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='params',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='script',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
