# Generated by Django 4.1.1 on 2023-02-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_task_params_task_script'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='scheduled_time',
        ),
        migrations.AddField(
            model_name='task',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='schedule_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
