# Generated by Django 4.1.1 on 2023-02-22 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0007_remove_task_scheduled_time_task_is_scheduled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='script',
        ),
    ]
