# Generated by Django 4.1.1 on 2023-02-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0008_remove_task_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='schedule_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
