# Generated by Django 4.1.1 on 2023-02-22 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0009_task_schedule_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='published_time',
            new_name='publish_time',
        ),
    ]
