# Generated by Django 4.1.1 on 2023-02-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0011_executor_scripts'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='script',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
