# Generated by Django 4.1.1 on 2023-03-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0012_task_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='executor',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
