# Generated by Django 4.1.1 on 2023-03-14 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0014_device_remove_target_comments_remove_target_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='target',
            unique_together={('device', 'executor')},
        ),
    ]
