# Generated by Django 4.1.1 on 2023-03-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0015_alter_target_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.CharField(blank=True, choices=[('Web Camera', 'Webcamera'), ('Data Acquisition Device', 'Daq'), ('Switch Box', 'Switchbox'), ('Digital Cockpit Head Unit', 'Dhu'), ('Phone', 'Phone'), ('Others', 'Others')], max_length=64, null=True),
        ),
    ]
