# Generated by Django 4.1.1 on 2022-12-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='office',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
