# Generated by Django 4.1.1 on 2022-12-22 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_office'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='office',
            new_name='department',
        ),
    ]
