# Generated by Django 4.1.1 on 2023-01-10 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userrole_userproject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProject',
        ),
    ]
