# Generated by Django 4.1.1 on 2023-01-10 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_userrole_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('visitor', 'Visitor'), ('editor', 'Editor')], default='visitor', max_length=64, null=True),
        ),
    ]
